### ISSUE TITLE
I lost my main account.

### ISSUE THREAD

**Issue by Murasame233** [algorand/algorand-wallet#47]
I update my application on google play when I am using test-net. After update, I switch back to main net, my main net account is missing, and on the wallet only have account from test net.

I think the update make the application choose the wrong table which between the main net and test net account.

I think you guys can offer a choice to export database.

I am using Samsung s10 5g. this phone is hard to root.
![2021-11-30 10 37 47](https://user-images.githubusercontent.com/87534732/143976667-d4c1e3f6-4d62-4da1-b4e5-cb301cf9a7b3.jpg)
![2021-11-30 10 37 55](https://user-images.githubusercontent.com/87534732/143976671-978a0b91-eb21-4047-8264-e01be8b711dd.jpg)
![2021-11-30 10 38 00](https://user-images.githubusercontent.com/87534732/143976672-1b750ec3-b124-45b1-9b48-19d1f83cde86.jpg)
![2021-11-30 10 38 04](https://user-images.githubusercontent.com/87534732/143976674-3972b618-a1d0-4436-929d-1ac4861bf6fb.jpg)

**Comment by mitsinsar** [comment]
Hi @Murasame233 

Migration has been checked twice. Seems no issue on migration side. 

By saying missing; 
1. You have one account called `original` with the address `U5ZBWCAOCYXO6L4LRXKQIAQSMLOYF746O2TAOESEDMGYSPEVBWTUS4QPPQ` and you are not able to see the balance?
2. You have another account and it doesn't show up in the list.

Which one matches with your case?

**Comment by Murasame233** [comment]
Thanks @mitsinsar .

The original account is create for test-net.
main-net account is missing after switch to main-net, and original account(it created on test-net) should be hidden after switch to main net.

Don't worry about my all account on main-net, I backup the memonic.
But when you have ton's acount on the main-net, the lost will makes you annoy.
You have to reimport all account.

**Comment by Murasame233** [comment]
I know why.
I think when add an account it will work on test-net and main-net, there is no isolation between main-net and test-net.

And when I switch to test-net, I think I have ton's of account should not be in there.  and I delete it.
